In [1]:
import pandas as pd
import numpy as np
import glob
import os

# inputs

In [2]:
input_idf_table_file_path = './Assignment_3__Input_FE/Data_Centroid/BOM_IDF_Data/depths_-33.8774_151.093_all_design.csv'
input_temp_pattern_file_path = './Assignment_3__Input_FE/Data_Centroid/ECsouth/ECsouth_Increments.csv'
input_storm_stats_file_path = './Assignment_3__Input_FE/Data_Centroid/ECsouth/ECsouth_AllStats.csv'
output_dir = './Assignment_3__Output_FE__1st__centroid/'

print(
    input_idf_table_file_path,
    input_temp_pattern_file_path,
    input_storm_stats_file_path,
    sep='\n'
    )

./Assignment_3__Input_FE/Data_Centroid/BOM_IDF_Data/depths_-33.8774_151.093_all_design.csv
./Assignment_3__Input_FE/Data_Centroid/ECsouth/ECsouth_Increments.csv
./Assignment_3__Input_FE/Data_Centroid/ECsouth/ECsouth_AllStats.csv


In [3]:
def create_output_dir(arg_output_dir):
    """create output directory if it does not exist

    arguments:
        [string] --> arg_output_dir = path of the output directory name
    """
    if not os.path.exists(arg_output_dir):
        os.makedirs(arg_output_dir)

In [4]:
create_output_dir(output_dir)
output_dir

'./Assignment_3__Output_FE__1st__centroid/'

# building idf table

In [5]:
idf_table = pd.read_csv(filepath_or_buffer=input_idf_table_file_path, skiprows=9)
frequency_label = idf_table.columns[2:].to_numpy()
idf_table.columns = idf_table.columns.to_series().apply(
    func=lambda arg: 
        '_'.join(arg.split(sep=' ')) 
        if arg[:8] == 'Duration' 
        else 'freq_' + '_'.join('_perc'.join('_'.join(arg.split(sep=' ')).split(sep='%')).split(sep='.'))
    )
frequency_tag = idf_table.columns[2:].to_numpy()
idf_table[['Duration', 'units']] = idf_table.apply(func=lambda arg: arg.Duration.split(sep=' '), axis=1, result_type='expand')
idf_table = idf_table[idf_table.columns[[0,-1] + list(range(1,len(idf_table.columns) - 1))]]
idf_table.Duration = idf_table.Duration.astype(float)
idf_table.to_csv(path_or_buf='{}table_idf_depths.csv'.format(output_dir), index=False)
idf_table.to_parquet(path='{}table_idf_depths.parquet'.format(output_dir))

idf_table

Duration units  Duration_in_min  freq_12EY  freq_6EY  freq_4EY  freq_3EY  \
0        1.0   min              1.0      0.999      1.13      1.37      1.55   
1        2.0   min              2.0      1.770      2.00      2.39      2.67   
2        3.0   min              3.0      2.410      2.73      3.29      3.68   
3        4.0   min              4.0      2.960      3.36      4.07      4.58   
4        5.0   min              5.0      3.430      3.91      4.76      5.37   
5       10.0   min             10.0      5.150      5.91      7.28      8.27   
6       15.0   min             15.0      6.290      7.25      8.96     10.20   
7       20.0   min             20.0      7.160      8.26     10.20     11.70   
8       25.0   min             25.0      7.860      9.07     11.20     12.80   
9       30.0   min             30.0      8.460      9.76     12.10     13.80   
10      45.0   min             45.0      9.860     11.40     14.10     16.10   
11       1.0  hour             60.0     10.900     12.60     15.60     17.80   
12       1.5  hour             90.0     12.600     14.50     18.00     20.50   
13       2.0  hour            120.0     13.900     16.00     19.80     22.60   
14       3.0  hour            180.0     16.000     18.50     22.90     26.20   
15       4.5  hour            270.0     18.400     21.30     26.50     30.40   
16       6.0  hour            360.0     20.400     23.70     29.50     33.90   
17       9.0  hour            540.0     23.600     27.50     34.50     39.70   
18      12.0  hour            720.0     26.100     30.50     38.50     44.50   
19      18.0  hour           1080.0     30.000     35.30     45.00     52.10   
20      24.0  hour           1440.0     33.000     39.10     50.00     58.10   
21      30.0  hour           1800.0     35.400     42.00     54.00     63.00   
22      36.0  hour           2160.0     37.300     44.50     57.40     67.10   
23      48.0  hour           2880.0     40.300     48.30     62.70     73.60   
24      72.0  hour           4320.0     44.000     53.20     69.80     82.30   
25      96.0  hour           5760.0     45.900     55.90     74.10     87.70   
26     120.0  hour           7200.0     46.900     57.60     76.90     91.40   
27     144.0  hour           8640.0     47.400     58.40     78.80     93.90   
28     168.0  hour          10080.0     47.500     58.90     80.10     95.80   

    freq_2EY  freq_63_2_perc  freq_50_perc  ...  freq_20_perc  freq_0_2EY  \
0       1.80            2.28          2.51  ...          3.25        3.31   
1       3.07            3.77          4.10  ...          5.14        5.25   
2       4.25            5.23          5.71  ...          7.21        7.35   
3       5.30            6.56          7.19  ...          9.15        9.33   
4       6.23            7.75          8.52  ...         10.90       11.10   
5       9.70           12.20         13.60  ...         17.60       18.00   
6      12.00           15.30         16.90  ...         22.00       22.50   
7      13.70           17.50         19.40  ...         25.20       25.70   
8      15.10           19.30         21.40  ...         27.70       28.30   
9      16.30           20.80         23.00  ...         29.70       30.30   
10     19.00           24.30         26.70  ...         34.30       35.00   
11     21.00           27.00         29.50  ...         37.70       38.50   
12     24.20           31.00         33.90  ...         43.00       43.90   
13     26.80           34.30         37.50  ...         47.50       48.40   
14     31.00           39.80         43.40  ...         55.10       56.20   
15     36.00           46.40         50.70  ...         64.90       66.20   
16     40.30           52.00         57.10  ...         73.70       75.20   
17     47.40           61.50         68.00  ...         89.20       91.00   
18     53.30           69.50         77.30  ...        103.00      105.00   
19     62.80           82.50         92.70  ...        126.00  

# building temporal pattern table

In [6]:
temp_pattern_table = pd.read_csv(filepath_or_buffer=input_temp_pattern_file_path)
temp_pattern_table.rename(columns=lambda arg: arg.strip(), inplace=True)
# temp_pattern_table.rename(columns={'Duration':'Duration_in_min'}, inplace=True)
temp_pattern_table.columns = pd.Index(data=temp_pattern_table.columns[:5].to_list() + ['Increment_{:02}'.format(ind) for ind in range(len(temp_pattern_table.columns[5:]))])
temp_pattern_table.to_csv(path_or_buf='{}table_temp_patterns.csv'.format(output_dir), index=False)
temp_pattern_table.to_parquet(path='{}table_temp_patterns.parquet'.format(output_dir))

temp_pattern_table

EventID  Duration  TimeStep              Region       AEP  Increment_00  \
0       4380        10         5  East Coast (South)  frequent         58.06   
1       4382        10         5  East Coast (South)  frequent         52.13   
2       4384        10         5  East Coast (South)  frequent         60.71   
3       4385        10         5  East Coast (South)  frequent         51.51   
4       4386        10         5  East Coast (South)  frequent         54.55   
..       ...       ...       ...                 ...       ...           ...   
715     2856     10080       180  East Coast (South)      rare          1.14   
716     5064     10080       180  East Coast (South)      rare          0.61   
717     5069     10080       180  East Coast (South)      rare          0.00   
718     5071     10080       180  East Coast (South)      rare          1.21   
719     5072     10080       180  East Coast (South)      rare          4.39   

     Increment_01  Increment_02  Increment_03  Increment_04  ...  \
0           41.94           NaN           NaN           NaN  ...   
1           47.87           NaN           NaN           NaN  ...   
2           39.29           NaN           NaN           NaN  ...   
3           48.49           NaN           NaN           NaN  ...   
4           45.45           NaN           NaN           NaN  ...   
..            ...           ...           ...           ...  ...   
715          1.80          1.36          1.29          3.20  ...   
716          0.93          0.26          0.04          2.91  ...   
717          0.00          0.00          1.06          0.04  ...   
718          0.00          0.00          0.00          0.00  ...   
719          3.88          8.46          5.38          3.14  ...   

     Increment_46  Increment_47  Increment_48  Increment_49  Increment_50  \
0             NaN           NaN           NaN           NaN           NaN   
1             NaN           NaN           NaN           NaN           NaN   
2             NaN           NaN           NaN           NaN           NaN   
3             NaN           NaN           NaN           NaN           NaN   
4             NaN           NaN           NaN           NaN           NaN   
..            ...           ...           ...           ...           ...   
715          0.01          0.01          0.02          0.03          0.32   
716          5.27          0.31          0.02          1.21          1.57   
717          0.22          0.20          0.57          0.06          2.06   
718          0.05          0.56          0.70          3.31          0.10   
719          0.00          0.01          2.75          1.18          0.00   

     Increment_51  Increment_52  Increment_53  Increment_54  Increment_55  
0             NaN           NaN           NaN           NaN           NaN  
1             NaN           NaN           NaN           NaN           NaN  
2             NaN           NaN           NaN           NaN           NaN  
3             NaN           NaN           NaN           NaN           NaN  
4             NaN           NaN           NaN           NaN           NaN  
..            ...           ...           ...           ...           ...  
715          0.17          0.52          0.00          0.02          0.00  
716          0.08          0.05          0.15          0.40          0.11  
717          0.00          0.03          0.18          0.12          3.09  
718          0.11          0.00          0.00          0.00          0.15  
719          0.02          3.68         11.40          4.88          6.28  

[720 rows x 61 columns]

In [7]:
temp_pattern_table.dtypes

EventID           int64
Duration          int64
TimeStep          int64
Region           object
AEP              object
                 ...   
Increment_51    float64
Increment_52    float64
Increment_53    float64
Increment_54    float64
Increment_55    float64
Length: 61, dtype: object

In [8]:
storm_stats_table = pd.read_csv(filepath_or_buffer=input_storm_stats_file_path)
storm_stats_table.rename(columns=lambda arg: arg.strip(), inplace=True)
for ind in [(' ','_'), ('(',''), (')',''), ('%','in_perc'), ('_No.','_Number'), ('_min','_in_min'), ('_mm','_in_mm')]:
    storm_stats_table.rename(columns=lambda arg: arg.replace(*ind), inplace=True)
# storm_stats_table.rename(columns={'Burst_Duration_in_min':'Duration_in_min'}, inplace=True)
storm_stats_table.dropna(axis=0, inplace=True)
storm_stats_table.Burst_Start_Date = pd.to_datetime(arg=storm_stats_table.Burst_Start_Date, format='%m/%d/%Y %H:%M')
storm_stats_table.Burst_End_Date = pd.to_datetime(arg=storm_stats_table.Burst_End_Date, format='%m/%d/%Y %H:%M')
storm_stats_table.Event_ID = storm_stats_table.Event_ID.astype(int)
storm_stats_table.Burst_Duration_in_min = storm_stats_table.Burst_Duration_in_min.astype(int)
storm_stats_table.Burst_Loading = storm_stats_table.Burst_Loading.astype(int)
storm_stats_table.DB_Event_Reference_Number = storm_stats_table.DB_Event_Reference_Number.astype(int)
storm_stats_table.DB_Pluviograph_Reference_Number = storm_stats_table.DB_Pluviograph_Reference_Number.astype(int)
storm_stats_table.to_csv(path_or_buf='{}table_storm_stats.csv'.format(output_dir), index=False)
storm_stats_table.to_parquet(path='{}table_storm_stats.parquet'.format(output_dir))

storm_stats_table

Event_ID              Region       Region_source  Burst_Duration_in_min  \
0        4380  East Coast (South)  East Coast (South)                     10   
1        4382  East Coast (South)  East Coast (South)                     10   
2        4384  East Coast (South)  East Coast (South)                     10   
3        4385  East Coast (South)  East Coast (South)                     10   
4        4386  East Coast (South)  East Coast (South)                     10   
..        ...                 ...                 ...                    ...   
715      2856  East Coast (South)  East Coast (North)                  10080   
716      5064  East Coast (South)  East Coast (North)                  10080   
717      5069  East Coast (South)  East Coast (North)                  10080   
718      5071  East Coast (South)  East Coast (North)                  10080   
719      5072  East Coast (South)  East Coast (North)                  10080   

     Burst_Loading  Original_Burst_Depth_in_mm AEP_Window  AEP_source_in_perc  \
0                1                       15.50   frequent             14.4679   
1                1                       18.80   frequent             14.4924   
2                1                       16.80   frequent             14.5144   
3                2                       18.50   frequent             15.6473   
4                2                       11.00   frequent             47.6798   
..             ...                         ...        ...                 ...   
715              1                      595.23       rare              1.0865   
716              2                      589.88       rare              1.2899   
717              2                      491.26       rare              2.7020   
718              2                      400.84       rare              2.9538   
719              2                      260.63       rare              3.1285   

       Burst_Start_Date      Burst_End_Date  DB_Event_Reference_Number  \
0   2009-03-25 17:45:00 2009-03-25 17:50:00                     113650   
1   1999-12-28 17:05:00 1999-12-28 17:10:00                      39777   
2   2005-02-04 09:30:00 2005-02-04 09:35:00                      42925   
3   1999-03-27 22:30:00 1999-03-27 22:35:00                     114063   
4   1993-04-28 14:05:00 1993-04-28 14:10:00                     113366   
..                  ...                 ...                        ...   
715 1996-05-01 00:05:00 1996-05-08 00:00:00                      26738   
716 1968-01-06 17:10:00 1968-01-13 17:05:00                      24711   
717 1968-01-06 04:10:00 1968-01-13 04:05:00                      23354   
718 1968-01-07 11:45:00 1968-01-14 11:40:00                      27412   
719 1954-02-05 00:50:00 1954-02-12 00:45:00                      23094   

     DB_Pluviograph_Reference_Number   Offical_Gauge      Lat      Long  
0                               1828  qcd_563064_233 -32.2375  150.6306  
1                                517      qcd_061250 -32.6296  151.5919  
2                                556      qcd_068102 -34.4869  150.4019  
3                               1835  qcd_563079_231 -33.7944  150.5083  
4                               1824  qcd_563056_231 -34.0333  150.2153  
..                               ...             ...      ...       ...  
715                              351      qcd_040223 -27.4178  153.1142  
716                              329      qcd_040093 -26.1831  152.6414  
717                              313      qcd_039128 -24.9069  152.3230  
718                              358      qcd_040318 -27.0258  152.5642  
719                              310      qcd_039090 -24.9503  150.0725  

[720 rows x 15 columns]

# building frequency classification table

In [9]:
ey_constants = np.array(object=[12,6,4,3,2,1,0.5,0.2])
ey_constants

array([12. ,  6. ,  4. ,  3. ,  2. ,  1. ,  0.5,  0.2])

In [10]:
aep_variables = np.multiply(np.add(1, np.negative(np.exp(np.negative(ey_constants)))),100)
aep_variables

array([99.99938558, 99.75212478, 98.16843611, 95.02129316, 86.46647168,
       63.21205588, 39.34693403, 18.12692469])

In [11]:
aep_constants = np.array(object=[50, 20, 10, 5, 2, 1, 0.5, 0.2, 0.1, 0.05, 0.02])
aep_constants

array([5.e+01, 2.e+01, 1.e+01, 5.e+00, 2.e+00, 1.e+00, 5.e-01, 2.e-01,
       1.e-01, 5.e-02, 2.e-02])

In [12]:
ey_variables = np.negative(np.log(np.add(1, np.negative(np.divide(aep_constants, 100)))))
ey_variables

array([6.93147181e-01, 2.23143551e-01, 1.05360516e-01, 5.12932944e-02,
       2.02027073e-02, 1.00503359e-02, 5.01254182e-03, 2.00200267e-03,
       1.00050033e-03, 5.00125042e-04, 2.00020003e-04])

In [13]:
ey = np.flip(m=np.sort(a=np.concatenate((ey_constants, ey_variables))))
ey

array([1.20000000e+01, 6.00000000e+00, 4.00000000e+00, 3.00000000e+00,
       2.00000000e+00, 1.00000000e+00, 6.93147181e-01, 5.00000000e-01,
       2.23143551e-01, 2.00000000e-01, 1.05360516e-01, 5.12932944e-02,
       2.02027073e-02, 1.00503359e-02, 5.01254182e-03, 2.00200267e-03,
       1.00050033e-03, 5.00125042e-04, 2.00020003e-04])

In [14]:
aep_percentage = np.flip(m=np.sort(a=np.concatenate((aep_constants, aep_variables))))
aep_percentage

array([9.99993856e+01, 9.97521248e+01, 9.81684361e+01, 9.50212932e+01,
       8.64664717e+01, 6.32120559e+01, 5.00000000e+01, 3.93469340e+01,
       2.00000000e+01, 1.81269247e+01, 1.00000000e+01, 5.00000000e+00,
       2.00000000e+00, 1.00000000e+00, 5.00000000e-01, 2.00000000e-01,
       1.00000000e-01, 5.00000000e-02, 2.00000000e-02])

In [15]:
aep_1_in_x = np.divide(100, aep_percentage)
aep_1_in_x

array([1.00000614e+00, 1.00248491e+00, 1.01865736e+00, 1.05239570e+00,
       1.15651764e+00, 1.58197671e+00, 2.00000000e+00, 2.54149408e+00,
       5.00000000e+00, 5.51665557e+00, 1.00000000e+01, 2.00000000e+01,
       5.00000000e+01, 1.00000000e+02, 2.00000000e+02, 5.00000000e+02,
       1.00000000e+03, 2.00000000e+03, 5.00000000e+03])

In [16]:
ari = np.divide(1,ey)
ari

array([8.33333333e-02, 1.66666667e-01, 2.50000000e-01, 3.33333333e-01,
       5.00000000e-01, 1.00000000e+00, 1.44269504e+00, 2.00000000e+00,
       4.48142012e+00, 5.00000000e+00, 9.49122158e+00, 1.94957257e+01,
       4.94983165e+01, 9.94991625e+01, 1.99499582e+02, 4.99499833e+02,
       9.99499917e+02, 1.99949996e+03, 4.99949998e+03])

In [17]:
aep_percentage

array([9.99993856e+01, 9.97521248e+01, 9.81684361e+01, 9.50212932e+01,
       8.64664717e+01, 6.32120559e+01, 5.00000000e+01, 3.93469340e+01,
       2.00000000e+01, 1.81269247e+01, 1.00000000e+01, 5.00000000e+00,
       2.00000000e+00, 1.00000000e+00, 5.00000000e-01, 2.00000000e-01,
       1.00000000e-01, 5.00000000e-02, 2.00000000e-02])

In [18]:
frequency_window = np.array(object=['frequent', 'intermediate', 'rare'])[
    np.add(np.digitize(x=aep_percentage, bins=np.array(object=[100, 14.4, 3.2, 0]), right=False), np.negative(1))
    ]
frequency_window

array(['frequent', 'frequent', 'frequent', 'frequent', 'frequent',
       'frequent', 'frequent', 'frequent', 'frequent', 'frequent',
       'intermediate', 'intermediate', 'rare', 'rare', 'rare', 'rare',
       'rare', 'rare', 'rare'], dtype='<U12')

In [19]:
frequency_tag = np.concatenate((frequency_tag, np.array(object=['freq_1_in_5000'])))
frequency_tag

array(['freq_12EY', 'freq_6EY', 'freq_4EY', 'freq_3EY', 'freq_2EY',
       'freq_63_2_perc', 'freq_50_perc', 'freq_0_5EY', 'freq_20_perc',
       'freq_0_2EY', 'freq_10_perc', 'freq_5_perc', 'freq_2_perc',
       'freq_1_perc', 'freq_1_in_200', 'freq_1_in_500', 'freq_1_in_1000',
       'freq_1_in_2000', 'freq_1_in_5000'], dtype=object)

In [20]:
frequency_label = np.concatenate((frequency_label, np.array(object=['1 in 5000'])))
frequency_label

array(['12EY', '6EY', '4EY', '3EY', '2EY', '63.2%', '50%', '0.5EY', '20%',
       '0.2EY', '10%', '5%', '2%', '1%', '1 in 200', '1 in 500',
       '1 in 1000', '1 in 2000', '1 in 5000'], dtype=object)

In [21]:
frequency_table = pd.DataFrame(
    data=np.column_stack(tup=(ey, aep_percentage, aep_1_in_x, ari, frequency_window, frequency_label, frequency_tag)),
    columns=['EY', 'AEP_percentage', 'AEP_1_in_x', 'ARI', 'freq_window', 'freq_label', 'freq_tag']
    )
frequency_table.to_csv(path_or_buf='{}table_frequency.csv'.format(output_dir), index=False)
frequency_table.to_parquet(path='{}table_frequency.parquet'.format(output_dir))
frequency_table

EY AEP_percentage AEP_1_in_x          ARI   freq_window freq_label  \
0       12.0      99.999386   1.000006     0.083333      frequent       12EY   
1        6.0      99.752125   1.002485     0.166667      frequent        6EY   
2        4.0      98.168436   1.018657         0.25      frequent        4EY   
3        3.0      95.021293   1.052396     0.333333      frequent        3EY   
4        2.0      86.466472   1.156518          0.5      frequent        2EY   
5        1.0      63.212056   1.581977          1.0      frequent      63.2%   
6   0.693147           50.0        2.0     1.442695      frequent        50%   
7        0.5      39.346934   2.541494          2.0      frequent      0.5EY   
8   0.223144           20.0        5.0      4.48142      frequent        20%   
9        0.2      18.126925   5.516656          5.0      frequent      0.2EY   
10  0.105361           10.0       10.0     9.491222  intermediate        10%   
11  0.051293            5.0       20.0    19.495726  intermediate         5%   
12  0.020203            2.0       50.0    49.498316          rare         2%   
13   0.01005            1.0      100.0    99.499162          rare         1%   
14  0.005013            0.5      200.0   199.499582          rare   1 in 200   
15  0.002002            0.2      500.0   499.499833          rare   1 in 500   
16  0.001001            0.1     1000.0   999.499917          rare  1 in 1000   
17    0.0005           0.05     2000.0  1999.499958          rare  1 in 2000   
18    0.0002           0.02     5000.0  4999.499983          rare  1 in 5000   

          freq_tag  
0        freq_12EY  
1         freq_6EY  
2         freq_4EY  
3         freq_3EY  
4         freq_2EY  
5   freq_63_2_perc  
6     freq_50_perc  
7       freq_0_5EY  
8     freq_20_perc  
9       freq_0_2EY  
10    freq_10_perc  
11     freq_5_perc  
12     freq_2_perc  
13     freq_1_perc  
14   freq_1_in_200  
15   freq_1_in_500  
16  freq_1_in_1000  
17  freq_1_in_2000  
18  freq_1_in_5000

In [22]:
r_ey = ey.copy()
r_ey[:14] = r_ey[:14].round(decimals=2)
r_ey[14:17] = r_ey[14:17].round(decimals=3)
r_ey[17:] = r_ey[17:].round(decimals=4)
r_ey

array([1.2e+01, 6.0e+00, 4.0e+00, 3.0e+00, 2.0e+00, 1.0e+00, 6.9e-01,
       5.0e-01, 2.2e-01, 2.0e-01, 1.1e-01, 5.0e-02, 2.0e-02, 1.0e-02,
       5.0e-03, 2.0e-03, 1.0e-03, 5.0e-04, 2.0e-04])

In [23]:
r_aep_percentage = aep_percentage.copy()
r_aep_percentage = r_aep_percentage.round(decimals=2)
r_aep_percentage

array([1.000e+02, 9.975e+01, 9.817e+01, 9.502e+01, 8.647e+01, 6.321e+01,
       5.000e+01, 3.935e+01, 2.000e+01, 1.813e+01, 1.000e+01, 5.000e+00,
       2.000e+00, 1.000e+00, 5.000e-01, 2.000e-01, 1.000e-01, 5.000e-02,
       2.000e-02])

In [24]:
r_aep_1_in_x = aep_1_in_x.copy()
r_aep_1_in_x[:2] = r_aep_1_in_x[:2].round(decimals=3)
r_aep_1_in_x[2:] = r_aep_1_in_x[2:].round(decimals=2)
r_aep_1_in_x

array([1.000e+00, 1.002e+00, 1.020e+00, 1.050e+00, 1.160e+00, 1.580e+00,
       2.000e+00, 2.540e+00, 5.000e+00, 5.520e+00, 1.000e+01, 2.000e+01,
       5.000e+01, 1.000e+02, 2.000e+02, 5.000e+02, 1.000e+03, 2.000e+03,
       5.000e+03])

In [25]:
r_ari = ari.copy()
r_ari = r_ari.round(decimals=2)
r_ari

array([8.0000e-02, 1.7000e-01, 2.5000e-01, 3.3000e-01, 5.0000e-01,
       1.0000e+00, 1.4400e+00, 2.0000e+00, 4.4800e+00, 5.0000e+00,
       9.4900e+00, 1.9500e+01, 4.9500e+01, 9.9500e+01, 1.9950e+02,
       4.9950e+02, 9.9950e+02, 1.9995e+03, 4.9995e+03])

In [26]:
r_frequency_table = pd.DataFrame(
    data=np.column_stack(tup=(r_ey, r_aep_percentage, r_aep_1_in_x, r_ari, frequency_window, frequency_label, frequency_tag)),
    columns=['EY', 'AEP_percentage', 'AEP_1_in_x', 'ARI', 'freq_window', 'freq_label', 'freq_tag']
    )
r_frequency_table.to_csv(path_or_buf='{}table_rounded_frequency.csv'.format(output_dir), index=False)
r_frequency_table.to_parquet(path='{}table_rounded_frequency.parquet'.format(output_dir))
r_frequency_table

EY AEP_percentage AEP_1_in_x     ARI   freq_window freq_label  \
0     12.0          100.0        1.0    0.08      frequent       12EY   
1      6.0          99.75      1.002    0.17      frequent        6EY   
2      4.0          98.17       1.02    0.25      frequent        4EY   
3      3.0          95.02       1.05    0.33      frequent        3EY   
4      2.0          86.47       1.16     0.5      frequent        2EY   
5      1.0          63.21       1.58     1.0      frequent      63.2%   
6     0.69           50.0        2.0    1.44      frequent        50%   
7      0.5          39.35       2.54     2.0      frequent      0.5EY   
8     0.22           20.0        5.0    4.48      frequent        20%   
9      0.2          18.13       5.52     5.0      frequent      0.2EY   
10    0.11           10.0       10.0    9.49  intermediate        10%   
11    0.05            5.0       20.0    19.5  intermediate         5%   
12    0.02            2.0       50.0    49.5          rare         2%   
13    0.01            1.0      100.0    99.5          rare         1%   
14   0.005            0.5      200.0   199.5          rare   1 in 200   
15   0.002            0.2      500.0   499.5          rare   1 in 500   
16   0.001            0.1     1000.0   999.5          rare  1 in 1000   
17  0.0005           0.05     2000.0  1999.5          rare  1 in 2000   
18  0.0002           0.02     5000.0  4999.5          rare  1 in 5000   

          freq_tag  
0        freq_12EY  
1         freq_6EY  
2         freq_4EY  
3         freq_3EY  
4         freq_2EY  
5   freq_63_2_perc  
6     freq_50_perc  
7       freq_0_5EY  
8     freq_20_perc  
9       freq_0_2EY  
10    freq_10_perc  
11     freq_5_perc  
12     freq_2_perc  
13     freq_1_perc  
14   freq_1_in_200  
15   freq_1_in_500  
16  freq_1_in_1000  
17  freq_1_in_2000  
18  freq_1_in_5000

# building timeseries

In [27]:
{key:val for key,val in enumerate(storm_stats_table.columns)}

{0: 'Event_ID',
 1: 'Region',
 2: 'Region_source',
 3: 'Burst_Duration_in_min',
 4: 'Burst_Loading',
 5: 'Original_Burst_Depth_in_mm',
 6: 'AEP_Window',
 7: 'AEP_source_in_perc',
 8: 'Burst_Start_Date',
 9: 'Burst_End_Date',
 10: 'DB_Event_Reference_Number',
 11: 'DB_Pluviograph_Reference_Number',
 12: 'Offical_Gauge',
 13: 'Lat',
 14: 'Long'}

In [161]:
df_storm_stats = storm_stats_table.copy()
df_storm_stats.drop(columns=storm_stats_table.columns[[1,2,4,5,7,8,9,10,11,12,13,14]], inplace=True)
df_storm_stats

Event_ID  Burst_Duration_in_min AEP_Window
0        4380                     10   frequent
1        4382                     10   frequent
2        4384                     10   frequent
3        4385                     10   frequent
4        4386                     10   frequent
..        ...                    ...        ...
715      2856                  10080       rare
716      5064                  10080       rare
717      5069                  10080       rare
718      5071                  10080       rare
719      5072                  10080       rare

[720 rows x 3 columns]

In [162]:
{key:val for key, val in enumerate(temp_pattern_table.columns)}

{0: 'EventID',
 1: 'Duration',
 2: 'TimeStep',
 3: 'Region',
 4: 'AEP',
 5: 'Increment_00',
 6: 'Increment_01',
 7: 'Increment_02',
 8: 'Increment_03',
 9: 'Increment_04',
 10: 'Increment_05',
 11: 'Increment_06',
 12: 'Increment_07',
 13: 'Increment_08',
 14: 'Increment_09',
 15: 'Increment_10',
 16: 'Increment_11',
 17: 'Increment_12',
 18: 'Increment_13',
 19: 'Increment_14',
 20: 'Increment_15',
 21: 'Increment_16',
 22: 'Increment_17',
 23: 'Increment_18',
 24: 'Increment_19',
 25: 'Increment_20',
 26: 'Increment_21',
 27: 'Increment_22',
 28: 'Increment_23',
 29: 'Increment_24',
 30: 'Increment_25',
 31: 'Increment_26',
 32: 'Increment_27',
 33: 'Increment_28',
 34: 'Increment_29',
 35: 'Increment_30',
 36: 'Increment_31',
 37: 'Increment_32',
 38: 'Increment_33',
 39: 'Increment_34',
 40: 'Increment_35',
 41: 'Increment_36',
 42: 'Increment_37',
 43: 'Increment_38',
 44: 'Increment_39',
 45: 'Increment_40',
 46: 'Increment_41',
 47: 'Increment_42',
 48: 'Increment_43',
 49: 'Inc

In [259]:
df_temp_pattern = temp_pattern_table.copy()
df_temp_pattern['time_series'] = df_temp_pattern.apply(func=lambda arg: arg.to_numpy()[5:], axis=1)
df_temp_pattern.drop(columns=df_temp_pattern.columns[5:-1], inplace=True)
df_temp_pattern.drop(columns='Region', inplace=True)
df_temp_pattern['id_count'] = pd.Series(data=list(np.arange(stop=10))*int(len(df_temp_pattern)/10))

df_temp_pattern

EventID  Duration  TimeStep       AEP  \
0       4380        10         5  frequent   
1       4382        10         5  frequent   
2       4384        10         5  frequent   
3       4385        10         5  frequent   
4       4386        10         5  frequent   
..       ...       ...       ...       ...   
715     2856     10080       180      rare   
716     5064     10080       180      rare   
717     5069     10080       180      rare   
718     5071     10080       180      rare   
719     5072     10080       180      rare   

                                           time_series  id_count  
0    [58.06, 41.94, nan, nan, nan, nan, nan, nan, n...         0  
1    [52.13, 47.87, nan, nan, nan, nan, nan, nan, n...         1  
2    [60.71, 39.29, nan, nan, nan, nan, nan, nan, n...         2  
3    [51.51, 48.49, nan, nan, nan, nan, nan, nan, n...         3  
4    [54.55, 45.45, nan, nan, nan, nan, nan, nan, n...         4  
..                                                 ...       ...  
715  [1.14, 1.8, 1.36, 1.29, 3.2, 4.78, 3.28, 3.13,...         5  
716  [0.61, 0.93, 0.26, 0.04, 2.91, 1.17, 4.05, 0.1...         6  
717  [0.0, 0.0, 0.0, 1.06, 0.04, 0.41, 0.71, 0.01, ...         7  
718  [1.21, 0.0, 0.0, 0.0, 0.0, 0.04, 0.52, 2.96, 1...         8  
719  [4.39, 3.88, 8.46, 5.38, 3.14, 1.92, 0.0, 0.0,...         9  

[720 rows x 6 columns]

In [260]:
df_temp_pattern.head(n=30)

EventID  Duration  TimeStep           AEP  \
0      4380        10         5      frequent   
1      4382        10         5      frequent   
2      4384        10         5      frequent   
3      4385        10         5      frequent   
4      4386        10         5      frequent   
5      4387        10         5      frequent   
6      4388        10         5      frequent   
7      4389        10         5      frequent   
8      4390        10         5      frequent   
9      4391        10         5      frequent   
10     4369        10         5  intermediate   
11     4370        10         5  intermediate   
12     4372        10         5  intermediate   
13     4373        10         5  intermediate   
14     4374        10         5  intermediate   
15     4375        10         5  intermediate   
16     4376        10         5  intermediate   
17     4377        10         5  intermediate   
18     4378        10         5  intermediate   
19     4379        10         5  intermediate   
20     4354        10         5          rare   
21     4355        10         5          rare   
22     4356        10         5          rare   
23     4357        10         5          rare   
24     4361        10         5          rare   
25     4363        10         5          rare   
26     4364        10         5          rare   
27     4365        10         5          rare   
28     4366        10         5          rare   
29     4368        10         5          rare   

                                          time_series  id_count  
0   [58.06, 41.94, nan, nan, nan, nan, nan, nan, n...         0  
1   [52.13, 47.87, nan, nan, nan, nan, nan, nan, n...         1  
2   [60.71, 39.29, nan, nan, nan, nan, nan, nan, n...         2  
3   [51.51, 48.49, nan, nan, nan, nan, nan, nan, n...         3  
4   [54.55, 45.45, nan, nan, nan, nan, nan, nan, n...         4  
5   [39.3, 60.7, nan, nan, nan, nan, nan, nan, nan...         5  
6   [45.0, 55.0, nan, nan, nan, nan, nan, nan, nan...         6  
7   [49.56, 50.44, nan, nan, nan, nan, nan, nan, n...         7  
8   [30.38, 69.62, nan, nan, nan, nan, nan, nan, n...         8  
9   [45.3, 54.7, nan, nan, nan, nan, nan, nan, nan...         9  
10  [55.22, 44.78, nan, nan, nan, nan, nan, nan, n...         0  
11  [64.14, 35.86, nan, nan, nan, nan, nan, nan, n...         1  
12  [50.55, 49.45, nan, nan, nan, nan, nan, nan, n...         2  
13  [42.72, 57.28, nan, nan, nan, nan, nan, nan, n...         3  
14  [47.92, 52.08, nan, nan, nan, nan, nan, nan, n...         4  
15  [48.92, 51.08, nan, nan, nan, nan, nan, nan, n...         5  
16  [49.41, 50.59, nan, nan, nan, nan, nan, nan, n...         6  
17  [46.47, 53.53, nan, nan, nan, nan, nan, nan, n...         7  
18  [52.27, 47.73, nan, nan, nan, nan, nan, nan, n...         8  
19  [59.29, 40.71, nan, nan, nan, nan, nan, nan, n...         9  
20  [60.56, 39.44, nan, nan, nan, nan, nan, nan, n...         0  
21  [61.2, 38.8, nan, nan, nan, nan, nan, nan, nan...         1  
22  [50.88, 49.12, nan, nan, nan, nan, nan, nan, n...         2  
23  [49.43, 50.57, nan, nan, nan, nan, nan, nan, n...         3  
24  [43.58, 56.42, nan, nan, nan, nan, nan, nan, n...         4  
25  [58.18, 41.82, nan, nan, nan, nan, nan, nan, n...         5  
26  [49.51, 50.49, nan, nan, nan, nan, nan, nan, n...         6  
27  [58.87, 41.13, nan, nan, nan, nan, nan, nan, n...         7  
28  [34.23, 65.77, nan, nan, nan, nan, nan, nan, n...         8  
29  [41.94, 58.06, nan, nan, nan, nan, nan, nan, n...         9

In [164]:
df_timeseries = pd.merge(left=df_storm_stats, right=df_temp_pattern, how='inner', left_on='Event_ID', right_on='EventID')
df_timeseries.drop(columns=['Event_ID', 'Burst_Duration_in_min', 'EventID', 'AEP'], inplace=True)
df_timeseries = df_timeseries[df_timeseries.columns[[2,1,0,3]]]
df_timeseries['id_window'] = pd.Series(data=np.unique(ar=df_timeseries.AEP_Window.to_numpy(), return_inverse=True)[1])

df_timeseries

TimeStep  Duration AEP_Window  \
0           5        10   frequent   
1           5        10   frequent   
2           5        10   frequent   
3           5        10   frequent   
4           5        10   frequent   
..        ...       ...        ...   
715       180     10080       rare   
716       180     10080       rare   
717       180     10080       rare   
718       180     10080       rare   
719       180     10080       rare   

                                           time_series  id_window  
0    [58.06, 41.94, nan, nan, nan, nan, nan, nan, n...          0  
1    [52.13, 47.87, nan, nan, nan, nan, nan, nan, n...          0  
2    [60.71, 39.29, nan, nan, nan, nan, nan, nan, n...          0  
3    [51.51, 48.49, nan, nan, nan, nan, nan, nan, n...          0  
4    [54.55, 45.45, nan, nan, nan, nan, nan, nan, n...          0  
..                                                 ...        ...  
715  [1.14, 1.8, 1.36, 1.29, 3.2, 4.78, 3.28, 3.13,...          2  
716  [0.61, 0.93, 0.26, 0.04, 2.91, 1.17, 4.05, 0.1...          2  
717  [0.0, 0.0, 0.0, 1.06, 0.04, 0.41, 0.71, 0.01, ...          2  
718  [1.21, 0.0, 0.0, 0.0, 0.0, 0.04, 0.52, 2.96, 1...          2  
719  [4.39, 3.88, 8.46, 5.38, 3.14, 1.92, 0.0, 0.0,...          2  

[720 rows x 5 columns]

In [172]:
df_timeseries.TimeStep.to_list()

[5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,


In [211]:
df_map = df_timeseries.copy().iloc[:,:2].drop_duplicates(subset=['TimeStep', 'Duration'])
df_map.reset_index(drop=True, inplace=True)
df_map = {key:val for key,val in zip(df_map.Duration, df_map.TimeStep)}

df_map

{10: 5,
 15: 5,
 20: 5,
 25: 5,
 30: 5,
 45: 5,
 60: 5,
 90: 5,
 120: 5,
 180: 15,
 270: 15,
 360: 15,
 540: 30,
 720: 30,
 1080: 60,
 1440: 60,
 1800: 120,
 2160: 120,
 2880: 120,
 4320: 180,
 5760: 180,
 7200: 180,
 8640: 180,
 10080: 180}

In [166]:
df_id = frequency_table.copy().iloc[:-1,4:]
df_id = pd.concat(objs=[
    pd.Series(data=['depth']*len(df_id)), 
    df_id,
    pd.Series(data=np.unique(ar=df_id.freq_window.to_numpy(), return_inverse=True)[1], name='id_window'),
    df_id.index.to_series(name='id_tag')
    ], axis=1)

df_id

0   freq_window freq_label        freq_tag  id_window  id_tag
0   depth      frequent       12EY       freq_12EY          0       0
1   depth      frequent        6EY        freq_6EY          0       1
2   depth      frequent        4EY        freq_4EY          0       2
3   depth      frequent        3EY        freq_3EY          0       3
4   depth      frequent        2EY        freq_2EY          0       4
5   depth      frequent      63.2%  freq_63_2_perc          0       5
6   depth      frequent        50%    freq_50_perc          0       6
7   depth      frequent      0.5EY      freq_0_5EY          0       7
8   depth      frequent        20%    freq_20_perc          0       8
9   depth      frequent      0.2EY      freq_0_2EY          0       9
10  depth  intermediate        10%    freq_10_perc          1      10
11  depth  intermediate         5%     freq_5_perc          1      11
12  depth          rare         2%     freq_2_perc          2      12
13  depth          rare         1%     freq_1_perc          2      13
14  depth          rare   1 in 200   freq_1_in_200          2      14
15  depth          rare   1 in 500   freq_1_in_500          2      15
16  depth          rare  1 in 1000  freq_1_in_1000          2      16
17  depth          rare  1 in 2000  freq_1_in_2000          2      17

In [219]:
df_idf = idf_table.copy()
df_idf = df_idf[df_idf.Duration_in_min >= 10]
df_idf.reset_index(drop=True, inplace=True)
df_idf.Duration = df_idf.Duration.astype(int)
df_idf.Duration_in_min = df_idf.Duration_in_min.astype(int)
df_idf.set_index(keys=df_idf.columns[:3].to_list(), inplace=True)
df_idf.columns = pd.MultiIndex.from_frame(df=df_id)
df_idf = df_idf.stack(level=[1,2,3,4,5], future_stack=True)
# df_idf.sort_values(by=['id_window', 'id_tag', 'Duration_in_min'], inplace=True)
df_idf.reset_index(inplace=True)
df_idf['time_step'] = df_idf.Duration_in_min.map(arg=df_map)

df_idf

0    Duration units  Duration_in_min freq_window freq_label        freq_tag  \
0          10   min               10    frequent       12EY       freq_12EY   
1          10   min               10    frequent        6EY        freq_6EY   
2          10   min               10    frequent        4EY        freq_4EY   
3          10   min               10    frequent        3EY        freq_3EY   
4          10   min               10    frequent        2EY        freq_2EY   
..        ...   ...              ...         ...        ...             ...   
427       168  hour            10080        rare         1%     freq_1_perc   
428       168  hour            10080        rare   1 in 200   freq_1_in_200   
429       168  hour            10080        rare   1 in 500   freq_1_in_500   
430       168  hour            10080        rare  1 in 1000  freq_1_in_1000   
431       168  hour            10080        rare  1 in 2000  freq_1_in_2000   

0    id_window  id_tag   depth  time_step  
0            0       0    5.15          5  
1            0       1    5.91          5  
2            0       2    7.28          5  
3            0       3    8.27          5  
4            0       4    9.70          5  
..         ...     ...     ...        ...  
427          2      13  462.00        180  
428          2      14  514.00        180  
429          2      15  578.00        180  
430          2      16  628.00        180  
431          2      17  677.00        180  

[432 rows x 10 columns]

In [221]:
df_timeseries.set_index(keys=['Duration', 'id_window', 'TimeStep'], inplace=True)
df_timeseries

AEP_Window  \
Duration id_window TimeStep              
10       0         5          frequent   
                   5          frequent   
                   5          frequent   
                   5          frequent   
                   5          frequent   
...                                ...   
10080    2         180            rare   
                   180            rare   
                   180            rare   
                   180            rare   
                   180            rare   

                                                                   time_series  
Duration id_window TimeStep                                                     
10       0         5         [58.06, 41.94, nan, nan, nan, nan, nan, nan, n...  
                   5         [52.13, 47.87, nan, nan, nan, nan, nan, nan, n...  
                   5         [60.71, 39.29, nan, nan, nan, nan, nan, nan, n...  
                   5         [51.51, 48.49, nan, nan, nan, nan, nan, nan, n...  
                   5         [54.55, 45.45, nan, nan, nan, nan, nan, nan, n...  
...                                                                        ...  
10080    2         180       [1.14, 1.8, 1.36, 1.29, 3.2, 4.78, 3.28, 3.13,...  
                   180       [0.61, 0.93, 0.26, 0.04, 2.91, 1.17, 4.05, 0.1...  
                   180       [0.0, 0.0, 0.0, 1.06, 0.04, 0.41, 0.71, 0.01, ...  
                   180       [1.21, 0.0, 0.0, 0.0, 0.0, 0.04, 0.52, 2.96, 1...  
                   180       [4.39, 3.88, 8.46, 5.38, 3.14, 1.92, 0.0, 0.0,...  

[720 rows x 2 columns]

In [227]:
df_timeseries.index.to_frame().reset_index(drop=True).drop_duplicates(subset=['Duration', 'id_window', 'TimeStep'])

Duration  id_window  TimeStep
0          10          0         5
10         10          1         5
20         10          2         5
30         15          0         5
40         15          1         5
..        ...        ...       ...
670      8640          1       180
680      8640          2       180
690     10080          0       180
700     10080          1       180
710     10080          2       180

[72 rows x 3 columns]

In [223]:
df_idf.set_index(keys=['Duration_in_min', 'id_window', 'time_step'], inplace=True)
df_idf

0                                    Duration units freq_window freq_label  \
Duration_in_min id_window time_step                                          
10              0         5                10   min    frequent       12EY   
                          5                10   min    frequent        6EY   
                          5                10   min    frequent        4EY   
                          5                10   min    frequent        3EY   
                          5                10   min    frequent        2EY   
...                                       ...   ...         ...        ...   
10080           2         180             168  hour        rare         1%   
                          180             168  hour        rare   1 in 200   
                          180             168  hour        rare   1 in 500   
                          180             168  hour        rare  1 in 1000   
                          180             168  hour        rare  1 in 2000   

0                                          freq_tag  id_tag   depth  
Duration_in_min id_window time_step                                  
10              0         5               freq_12EY       0    5.15  
                          5                freq_6EY       1    5.91  
                          5                freq_4EY       2    7.28  
                          5                freq_3EY       3    8.27  
                          5                freq_2EY       4    9.70  
...                                             ...     ...     ...  
10080           2         180           freq_1_perc      13  462.00  
                          180         freq_1_in_200      14  514.00  
                          180         freq_1_in_500      15  578.00  
                          180        freq_1_in_1000      16  628.00  
                          180        freq_1_in_2000      17  677.00  

[432 rows x 7 columns]

In [228]:
df_idf.index.to_frame().reset_index(drop=True).drop_duplicates(subset=['Duration_in_min', 'id_window', 'time_step'])

Duration_in_min  id_window  time_step
0                 10          0          5
10                10          1          5
12                10          2          5
18                15          0          5
28                15          1          5
..               ...        ...        ...
406             8640          1        180
408             8640          2        180
414            10080          0        180
424            10080          1        180
426            10080          2        180

[72 rows x 3 columns]

In [243]:
asdasd = pd.merge(left=df_timeseries, right=df_idf, how='cross')
# asdasd.drop_duplicates(subset=['AEP_Window', 'Duration', 'id_tag'], inplace=True)
asdasd.drop_duplicates(subset=['time_series', 'AEP_Window', 'Duration', 'id_tag'], inplace=True)
asdasd

TypeError: unhashable type: 'numpy.ndarray'

In [ ]:
asd

In [185]:
df_idf.head(n=18)

0   Duration units  Duration_in_min   freq_window freq_label        freq_tag  \
0         10   min               10      frequent       12EY       freq_12EY   
1         10   min               10      frequent        6EY        freq_6EY   
2         10   min               10      frequent        4EY        freq_4EY   
3         10   min               10      frequent        3EY        freq_3EY   
4         10   min               10      frequent        2EY        freq_2EY   
5         10   min               10      frequent      63.2%  freq_63_2_perc   
6         10   min               10      frequent        50%    freq_50_perc   
7         10   min               10      frequent      0.5EY      freq_0_5EY   
8         10   min               10      frequent        20%    freq_20_perc   
9         10   min               10      frequent      0.2EY      freq_0_2EY   
10        10   min               10  intermediate        10%    freq_10_perc   
11        10   min               10  intermediate         5%     freq_5_perc   
12        10   min               10          rare         2%     freq_2_perc   
13        10   min               10          rare         1%     freq_1_perc   
14        10   min               10          rare   1 in 200   freq_1_in_200   
15        10   min               10          rare   1 in 500   freq_1_in_500   
16        10   min               10          rare  1 in 1000  freq_1_in_1000   
17        10   min               10          rare  1 in 2000  freq_1_in_2000   

0   id_window  id_tag  depth  time_step  
0           0       0   5.15          5  
1           0       1   5.91          5  
2           0       2   7.28          5  
3           0       3   8.27          5  
4           0       4   9.70          5  
5           0       5  12.20          5  
6           0       6  13.60          5  
7           0       7  15.10          5  
8           0       8  17.60          5  
9           0       9  18.00          5  
10          1      10  20.40          5  
11          1      11  23.00          5  
12          2      12  26.40          5  
13          2      13  29.00          5  
14          2      14  31.60          5  
15          2      15  35.80          5  
16          2      16  39.00          5  
17          2      17  42.20          5

In [183]:
df_timeseries.head(n=30)

TimeStep  Duration    AEP_Window  \
0          5        10      frequent   
1          5        10      frequent   
2          5        10      frequent   
3          5        10      frequent   
4          5        10      frequent   
5          5        10      frequent   
6          5        10      frequent   
7          5        10      frequent   
8          5        10      frequent   
9          5        10      frequent   
10         5        10  intermediate   
11         5        10  intermediate   
12         5        10  intermediate   
13         5        10  intermediate   
14         5        10  intermediate   
15         5        10  intermediate   
16         5        10  intermediate   
17         5        10  intermediate   
18         5        10  intermediate   
19         5        10  intermediate   
20         5        10          rare   
21         5        10          rare   
22         5        10          rare   
23         5        10          rare   
24         5        10          rare   
25         5        10          rare   
26         5        10          rare   
27         5        10          rare   
28         5        10          rare   
29         5        10          rare   

                                          time_series  id_window  
0   [58.06, 41.94, nan, nan, nan, nan, nan, nan, n...          0  
1   [52.13, 47.87, nan, nan, nan, nan, nan, nan, n...          0  
2   [60.71, 39.29, nan, nan, nan, nan, nan, nan, n...          0  
3   [51.51, 48.49, nan, nan, nan, nan, nan, nan, n...          0  
4   [54.55, 45.45, nan, nan, nan, nan, nan, nan, n...          0  
5   [39.3, 60.7, nan, nan, nan, nan, nan, nan, nan...          0  
6   [45.0, 55.0, nan, nan, nan, nan, nan, nan, nan...          0  
7   [49.56, 50.44, nan, nan, nan, nan, nan, nan, n...          0  
8   [30.38, 69.62, nan, nan, nan, nan, nan, nan, n...          0  
9   [45.3, 54.7, nan, nan, nan, nan, nan, nan, nan...          0  
10  [55.22, 44.78, nan, nan, nan, nan, nan, nan, n...          1  
11  [64.14, 35.86, nan, nan, nan, nan, nan, nan, n...          1  
12  [50.55, 49.45, nan, nan, nan, nan, nan, nan, n...          1  
13  [42.72, 57.28, nan, nan, nan, nan, nan, nan, n...          1  
14  [47.92, 52.08, nan, nan, nan, nan, nan, nan, n...          1  
15  [48.92, 51.08, nan, nan, nan, nan, nan, nan, n...          1  
16  [49.41, 50.59, nan, nan, nan, nan, nan, nan, n...          1  
17  [46.47, 53.53, nan, nan, nan, nan, nan, nan, n...          1  
18  [52.27, 47.73, nan, nan, nan, nan, nan, nan, n...          1  
19  [59.29, 40.71, nan, nan, nan, nan, nan, nan, n...          1  
20  [60.56, 39.44, nan, nan, nan, nan, nan, nan, n...          2  
21  [61.2, 38.8, nan, nan, nan, nan, nan, nan, nan...          2  
22  [50.88, 49.12, nan, nan, nan, nan, nan, nan, n...          2  
23  [49.43, 50.57, nan, nan, nan, nan, nan, nan, n...          2  
24  [43.58, 56.42, nan, nan, nan, nan, nan, nan, n...          2  
25  [58.18, 41.82, nan, nan, nan, nan, nan, nan, n...          2  
26  [49.51, 50.49, nan, nan, nan, nan, nan, nan, n...          2  
27  [58.87, 41.13, nan, nan, nan, nan, nan, nan, n...          2  
28  [34.23, 65.77, nan, nan, nan, nan, nan, nan, n...          2  
29  [41.94, 58.06, nan, nan, nan, nan, nan, nan, n...          2

In [171]:
df_idf.time_step.to_list()

[5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 15,
 15,
 15,
 30,
 30,
 60,
 60,
 120,
 120,
 120,
 180,
 180,
 180,
 180,
 180,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 15,
 15,
 15,
 30,
 30,
 60,
 60,
 120,
 120,
 120,
 180,
 180,
 180,
 180,
 180,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 15,
 15,
 15,
 30,
 30,
 60,
 60,
 120,
 120,
 120,
 180,
 180,
 180,
 180,
 180,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 15,
 15,
 15,
 30,
 30,
 60,
 60,
 120,
 120,
 120,
 180,
 180,
 180,
 180,
 180,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 15,
 15,
 15,
 30,
 30,
 60,
 60,
 120,
 120,
 120,
 180,
 180,
 180,
 180,
 180,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 15,
 15,
 15,
 30,
 30,
 60,
 60,
 120,
 120,
 120,
 180,
 180,
 180,
 180,
 180,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 15,
 15,
 15,
 30,
 30,
 60,
 60,
 120,
 120,
 120,
 180,
 180,
 180,
 180,
 180,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 15,
 15,
 15,
 30,
 30,
 60,
 60,
 120,
 120,
 120,
 180,
 180,
 180,
 180,
 180,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 15,
 15,
 1

In [169]:
a =0
b = 30
df_idf.iloc[a:a+b]

0   Duration units  Duration_in_min freq_window freq_label   freq_tag  \
0         10   min               10    frequent       12EY  freq_12EY   
1         15   min               15    frequent       12EY  freq_12EY   
2         20   min               20    frequent       12EY  freq_12EY   
3         25   min               25    frequent       12EY  freq_12EY   
4         30   min               30    frequent       12EY  freq_12EY   
5         45   min               45    frequent       12EY  freq_12EY   
6          1  hour               60    frequent       12EY  freq_12EY   
7          1  hour               90    frequent       12EY  freq_12EY   
8          2  hour              120    frequent       12EY  freq_12EY   
9          3  hour              180    frequent       12EY  freq_12EY   
10         4  hour              270    frequent       12EY  freq_12EY   
11         6  hour              360    frequent       12EY  freq_12EY   
12         9  hour              540    frequent       12EY  freq_12EY   
13        12  hour              720    frequent       12EY  freq_12EY   
14        18  hour             1080    frequent       12EY  freq_12EY   
15        24  hour             1440    frequent       12EY  freq_12EY   
16        30  hour             1800    frequent       12EY  freq_12EY   
17        36  hour             2160    frequent       12EY  freq_12EY   
18        48  hour             2880    frequent       12EY  freq_12EY   
19        72  hour             4320    frequent       12EY  freq_12EY   
20        96  hour             5760    frequent       12EY  freq_12EY   
21       120  hour             7200    frequent       12EY  freq_12EY   
22       144  hour             8640    frequent       12EY  freq_12EY   
23       168  hour            10080    frequent       12EY  freq_12EY   
24        10   min               10    frequent        6EY   freq_6EY   
25        15   min               15    frequent        6EY   freq_6EY   
26        20   min               20    frequent        6EY   freq_6EY   
27        25   min               25    frequent        6EY   freq_6EY   
28        30   min               30    frequent        6EY   freq_6EY   
29        45   min               45    frequent        6EY   freq_6EY   

0   id_window  id_tag  depth  time_step  
0           0       0   5.15          5  
1           0       0   6.29          5  
2           0       0   7.16          5  
3           0       0   7.86          5  
4           0       0   8.46          5  
5           0       0   9.86          5  
6           0       0  10.90          5  
7           0       0  12.60          5  
8           0       0  13.90          5  
9           0       0  16.00         15  
10          0       0  18.40         15  
11          0       0  20.40         15  
12          0       0  23.60         30  
13          0       0  26.10         30  
14          0       0  30.00         60  
15          0       0  33.00         60  
16          0       0  35.40        120  
17          0       0  37.30        120  
18          0       0  40.30        120  
19          0       0  44.00        180  
20          0       0  45.90        180  
21          0       0  46.90        180  
22          0       0  47.40        180  
23          0       0  47.50        180  
24          0       1   5.91          5  
25          0       1   7.25          5  
26          0       1   8.26          5  
27          0       1   9.07          5  
28          0       1   9.76          5  
29          0       1  11.40          5